import MenuDashboard from '@/compoments/menuDashboard'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PageStyles from '../../styles/pageAdmin.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={PageStyles.pageContainer}>
        <div className={PageStyles.pageBox}>
            <MenuDashboard/>
            {children}
        </div>
    </div>
      </body>
    </html>
  )
}